/**
 * The abstract RegistryItem class to be stored within a Registry.
 *
 * @public
 */
abstract class RegistryItem<Data, Immutable, Serial> {
  /**
   * Local mutable data for this RegistryItem.
   */
  protected data: Data;

  /**
   * Construct a new RegistryItem.
   *
   * @param serial - Serialized RegistryItem.
   */
  constructor(serial: Serial) {
    this.deserialize(serial);
  }

  /**
   * Deserialize a RegistryItem Serial into this RegistryItem.
   *
   * @remarks
   * This should clear the object prior to deserialization.
   *
   * @param serial - Serialized RegistryItem.
   */
  public abstract deserialize(serial: Serial): this

  /**
   * Generate an immutable Object from this RegistryItem.
   *
   * @remarks
   * This should include all useful information associated with this RegistryItem.
   */
  public abstract immute(): Immutable

  /**
   * Generate a transferable serial for this RegistryItem.
   *
   * @remarks
   * The Serial generated by this method should be a transferable JSON Object.
   */
  public abstract serialize(): Serial
}

export default RegistryItem;
